wait for openstorage deployment
Signed-off-by: Grant Griffiths <grant@portworx.com>

diff --git a/.github/workflows/kind-testing.yml b/.github/workflows/kind-testing.yml
--- a/.github/workflows/kind-testing.yml
+++ b/.github/workflows/kind-testing.yml
@@ -74,6 +74,20 @@ jobs:
       run: |
         kubectl cluster-info
         kubectl get pods -n kube-system
+        expected_running_pods=4
+        cnt=0
+        while [ "$(kubectl get pods -n kube-system | grep 'openstorage-' | grep 'Running' -c)" -lt "$expected_running_pods" ]; do
+          if [ $cnt -gt 15 ]; then
+              echo "openstorage pod status:"
+              kubectl describe pods -n kube-system
+              echo >&2 "ERROR: openstorage not ready after over 2.5 mins"
+              exit 1
+          fi
+          kubectl get pods -n kube-system | grep 'openstorage-'
+          echo "$(date +%H:%M:%S)" "waiting for openstorage deployment to complete, attempt #$cnt"
+        cnt=$((cnt + 1))
+          sleep 10   
+        done
 
     - name: Run tests
       run: |
